### ISSUE TITLE
Error importing pester module from psake

### ISSUE THREAD

**Issue by csharris** [psake/psake#180]
Hello!
I'm struggling with importing Pester and creating a psake task that can run tests. I'm not exactly sure how psake imports modules, but it seems to conflict with how pester is creating objects. Here is my setup:

psake-config.ps1:

```
$config.modules=(
    "..\PSModules\Pester"
)
$config.verboseError=$true
```

stage.ps1:

```
Task Default -Depends Test
Task Test {
    $testResults = Invoke-Pester -Path $PSScriptRoot -PassThru
    if ($testResults.FailedCount -gt 0) {
        $testResults | Format-List
        Write-Error -Message 'One or more Pester tests failed!'
    }
}
```

And I get the following exception from Pester:

```
5/10/2016 12:29:50 PM: An Error Occurred. See Error Details Below:
----------------------------------------------------------------------
 +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ [<<==>>] Exception: The property 'CommandCovera
ge' cannot be found on this object. Verify that the property exists and can be set.
----------------------------------------------------------------------

ErrorRecord:

PSMessageDetails      :
Exception             : System.Management.Automation.RuntimeException: The property 'CommandCoverage' cannot be found
                        on this object. Verify that the property exists and can be set.
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext
                        funcContext, Exception exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame
                        frame)
                           at
                        System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                        frame)
                           at
                        System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                        frame)
                           at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                           at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object
                        dollarUnderbar, Object inputToProcess)
                           at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
                           at System.Management.Automation.CommandProcessorBase.Complete()
TargetObject          :
CategoryInfo          : InvalidOperation: (:) [Enter-CoverageAnalysis], RuntimeException
FullyQualifiedErrorId : PropertyNotFound,Enter-CoverageAnalysis
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Enter-CoverageAnalysis, C:\git\ops\release-scripts\PSModules\Pester\Functions\Coverage.ps1:
                        line 29
                        at Invoke-Pester, C:\git\ops\release-scripts\PSModules\Pester\Pester.psm1: line 266
                        at <ScriptBlock>, C:\git\ops\release-scripts\staging\stage.ps1: line 33
                        at Invoke-Task, C:\git\ops\release-scripts\PSModules\psake\psake.psm1: line 99
                        at Invoke-Task, C:\git\ops\release-scripts\PSModules\psake\psake.psm1: line 125
                        at <ScriptBlock>, C:\git\ops\release-scripts\PSModules\psake\psake.psm1: line 400
                        at ExecuteInBuildFileScope, C:\git\ops\release-scripts\PSModules\psake\psake.psm1: line 697
                        at Invoke-psake, C:\git\ops\release-scripts\PSModules\psake\psake.psm1: line 361
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

I'm using psake 4.6.0 and Pester 3.4.0. This problem seems to only exist when I try to import the module using psake. Importing Pester beforehand doesn't seem to cause the issue at all.

Any guidance would be gladly appreciated, and perhaps if this issue is not relevant to psake's inner workings, I can post on the Pester issue board.

**Comment by dlwyatt** [comment]
I wasn't able to reproduce the problem, using the same version of psake / Pester.  Not sure what's going on here.

**Comment by csharris** [comment]
@dlwyatt 
Thanks for taking a look. 
Just to be complete, I made [this repository](https://github.com/csharris/psake-pester-test) to make sure we're on the same page. I was able to reproduce the problem on a couple different machines using both Powershell 4 and Powershell 5.

**Comment by dlwyatt** [comment]
Still wasn't able to repro.  :(

```
C:\Users\dlwya_000\Documents\GitHub
λ git clone https://github.com/csharris/psake-pester-test.git
Cloning into 'psake-pester-test'...
remote: Counting objects: 240, done.
remote: Compressing objects: 100% (201/201), done.
remote: Total 240 (delta 32), reused 239 (delta 31), pack-reused 0R
Receiving objects: 100% (240/240), 1.12 MiB | 0 bytes/s, done.
Resolving deltas: 100% (32/32), done.
Checking connectivity... done.
C:\Users\dlwya_000\Documents\GitHub
λ cd .\psake-pester-test\
C:\Users\dlwya_000\Documents\GitHub\psake-pester-test [master]
λ ls


    Directory: C:\Users\dlwya_000\Documents\GitHub\psake-pester-test


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        5/10/2016   4:24 PM                Pester
d-----        5/10/2016   4:24 PM                psake
-a----        5/10/2016   4:24 PM            302 default.ps1
-a----        5/10/2016   4:24 PM             82 default.tests.ps1
-a----        5/10/2016   4:24 PM             64 psake-config.ps1


C:\Users\dlwya_000\Documents\GitHub\psake-pester-test [master]
λ invoke-psake
psake version 4.6.0
Copyright (c) 2010-2014 James Kovacs & Contributors

Loading module: C:\Users\dlwya_000\Documents\GitHub\psake-pester-test\Pester

Executing Test





Describing Test
 [+] Tests 89ms
Tests completed in 89ms
Passed: 1 Failed: 0 Skipped: 0 Pending: 0 Inconclusive: 0

Build Succeeded!

----------------------------------------------------------------------
Build Time Report
----------------------------------------------------------------------
Name   Duration
----   --------
Test   00:00:00.1511335
Total: 00:00:00.1533883
C:\Users\dlwya_000\Documents\GitHub\psake-pester-test [master]
```

**Comment by dlwyatt** [comment]
I'm just running a plain Windows 10 system, by the way (currently PS version 5.0.10586.122 ).  No insider builds or anything like that.

**Comment by csharris** [comment]
In the case of Windows 10, I think Pester comes installed by default (version 3.3.5). Would you mind running ```Get-Module```?

Also, I found that if I run ```Install-Module Pester -Force``` on Windows 10, pester is then added to ```C:\ProgramFiles\WindowsPowershell\Modules\Pester\3.4.0```. If I restart powershell and then run psake, everything works fine. Unfortunately, this isn't a viable option for me.

**Comment by dragon788** [comment]
@csharris the restart isn't a viable option or performing an upgrade? You could install the newer version via something like Chocolatey and then just call powershell.exe ./psake.ps1 so it will be in the path when psake gets called.
